query PopularUsers($query: String!) {
  search(query: $query, type: USER, first: 50) {
    nodes {
      ... on User {
        login
        name
        followers {
          totalCount
        }
        createdAt
      }
    }
  }
}
